// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"geo-search/cmd/migration/client"
	"geo-search/internal/config"
	"geo-search/internal/connectors"
	"geo-search/internal/di"
	"github.com/google/wire"
)

// Injectors from migration_wire.go:

func InitializeMigration() *client.DatabaseClient {
	commandConfig := config.WireCommandConfig()
	configLoaderImpl := config.WireConfigLoader(commandConfig)
	mongoConfig := config.WireMongoConfig(configLoaderImpl)
	mongoConnector := connectors.WireMongoConnector(mongoConfig)
	elasticsearchConfig := config.WireElasticsearchConfig(configLoaderImpl)
	elasticSearchConnector := connectors.WireElasticsearchConnector(elasticsearchConfig)
	databaseClient := client.WireDatabaseClient(mongoConnector, elasticSearchConnector)
	return databaseClient
}

// migration_wire.go:

var MigrationSet = wire.NewSet(client.WireDatabaseClient, di.ConfigSet, di.ConnectorSet)
