// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"geo-search/cmd/http_api/server"
	"geo-search/internal/config"
	"geo-search/internal/connectors"
	"geo-search/internal/datasources"
	"geo-search/internal/di"
	"geo-search/internal/interactors"
	"geo-search/internal/transports/http"
	"github.com/google/wire"
)

// Injectors from api_wire.go:

func InitializeAPI() *server.ApiServer {
	commandConfig := config.WireCommandConfig()
	configLoaderImpl := config.WireConfigLoader(commandConfig)
	elasticsearchConfig := config.WireElasticsearchConfig(configLoaderImpl)
	elasticSearchConnector := connectors.WireElasticsearchConnector(elasticsearchConfig)
	mongoConfig := config.WireMongoConfig(configLoaderImpl)
	mongoConnector := connectors.WireMongoConnector(mongoConfig)
	estateDatasource := datasources.WireEstateDatasource(elasticSearchConnector, mongoConnector)
	estateInteractor := interactors.WireEstateInteractor(estateDatasource)
	estateController := http.WireEstateController(estateInteractor)
	apiRoutes := server.ProvideApiRoutes(estateController)
	apiServer := server.ProvideApiServer(apiRoutes)
	return apiServer
}

// api_wire.go:

var ApiSet = wire.NewSet(server.ProvideApiRoutes, server.ProvideApiServer, di.ConfigSet, di.ConnectorSet, di.HttpControllerSet, di.InteractorSet, di.RepositorySet)
