// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"geo-search/cmd/grpc_api/server"
	"geo-search/internal/config"
	"geo-search/internal/connectors"
	"geo-search/internal/datasources"
	"geo-search/internal/di"
	"geo-search/internal/interactors"
	"geo-search/internal/transports/grpc"
	"github.com/google/wire"
)

// Injectors from grpc_wire.go:

func InitializeGrpc() *server.GrpcServer {
	commandConfig := config.WireCommandConfig()
	configLoaderImpl := config.WireConfigLoader(commandConfig)
	elasticsearchConfig := config.WireElasticsearchConfig(configLoaderImpl)
	elasticSearchConnector := connectors.WireElasticsearchConnector(elasticsearchConfig)
	mongoConfig := config.WireMongoConfig(configLoaderImpl)
	mongoConnector := connectors.WireMongoConnector(mongoConfig)
	estateDatasource := datasources.WireEstateDatasource(elasticSearchConnector, mongoConnector)
	estateInteractor := interactors.WireEstateInteractor(estateDatasource)
	estateController := grpc.WireEstateController(estateInteractor)
	grpcServer := server.WireGrpcServer(estateController)
	return grpcServer
}

// grpc_wire.go:

var grpcSet = wire.NewSet(server.WireGrpcServer, di.GrpcControllerSet, di.ConfigSet, di.ConnectorSet, di.InteractorSet, di.RepositorySet)
